= Workshop: Mehr aus Ihren Fotos machen – Digitale Bildbearbeitung leicht gemacht
:author_1: Pro Senectute Luzern
:author_2: Jürg Luthiger
:revnumber: 1.0

* Zielgruppe: *Senior:innen*  
* Dauer: *2 Kurstage à 2½ Stunden*  
* Software: Systemeigene Programme  


== Voraussetzungen 

xref:voraussetzungen.adoc[Voraussetzungen für die Teilnahme am Kurs]

xref:gallery.adoc[Bildergalerie mit Beispielbildern zum Üben]

== Kursunterlagen

Zusätzlich zu den Arbeitsblättern, die an den beiden Kurstagen besprochen werden, ist es empfehlenswert, sich auch Gedanken über das eigene Setup zu machen. Hierfür steht eine xref:mein-setup.pdf[Vorlage] zur Verfügung, die eigenständig oder gemeinsam mit dem Kursleiter ausgefüllt werden kann.

Die Vorlage enthält unter anderem folgende Leitfragen, die bei der Vorbereitung hilfreich sind:

. *Kennen Sie Ihren Cloud-Dienst?* +
Welcher Anbieter? Welche Funktionen nutzen Sie bereits?

. *Haben Sie Ihren Benutzeraccount?* +
Zugangsdaten, Postfach, Rechte etc.

. *Kennen Sie die URL des Cloud-Diensts?* +
damit Sie sich direkt einloggen können.

. *Nutzen Sie ein iOS- oder Android-Smartphone?* +
Je nach System sind bestimmte Abläufe unterschiedlich.

. *Sind USB-Verbindungen zwischen den Geräten erlaubt?* +
Insbesondere bei Android-Geräten relevant.

. *Wissen Sie, wohin Sie neue Fotos kopieren wollen?* +
z.B. ein Verzeichnis auf Ihrem Windows-Rechner, ein Ordner in der Cloud etc.

Diese Fragen dienen als Orientierung, damit Sie Ihr Setup (Geräte, Verbindungen, Speicherorte usw.) klären und optimieren können. So stellen Sie sicher, dass technische Stolpersteine frühzeitig erkannt und vermieden werden.

== Tag 1 – Fotos importieren, speichern & organisieren

xref:arbeitsblatt1.adoc[Arbeitsblatt 1 – Fotos importieren und speichern]

xref:arbeitsblatt2.adoc[Arbeitsblatt 2 – Fotos organisieren]

== Tag 2 – Fotos bearbeiten

xref:arbeitsblatt3.adoc[Arbeitsblatt 3 – Fotos bearbeiten]

xref:abschluss_fotokurs.adoc[Arbeitsblatt 4 - Zum Vertiefen und Üben im und nach dem Kurs]

=== Wissenswertes

* xref:begriffe.adoc[Mediathek & Alben unter Windows 11]
* xref:cloud-services.adoc[Vergleich der Fotosynchronisation und Cloud-Speicherangebote]
* xref:bildformate.adoc[Vergleich gängiger Bildformate]
