name: Build and Deploy Asciidoctor site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Convert .adoc to HTML
        run: |
          mkdir -p build
          asciidoctor -D build index.adoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
